Feature branch
VVolchenkov/mobile-monitoring pull request #1
Opened 2022-06-22 14:41 UTC by VVolchenkov

2022-06-22 15:22 UTC, pavelpykhtin requested changes

2022-06-22 15:22 UTC, pavelpykhtin commented on src/Web/Controllers/DevicesController.cs
> +        if (Devices.Count <= 0)
Если следовать REST, то тут стоит возвращать пустой список. Как ресурс он существует, хоть и без наполнения.

2022-06-22 15:22 UTC, pavelpykhtin commented on src/Web/Controllers/DevicesController.cs
> +        if (Devices.TryGetValue(device.Id, out _))
Этот метод лучше удалить и оставить только UpdateDevice, т.к. в сценарии мониторинга устройство не обязано знать/помнить заводили его на сервере мониторинга или нет.

2022-06-22 15:22 UTC, pavelpykhtin commented on src/Web/Program.cs
> +builder.Host.UseSerilog((_, lc) =>
Btw: У нас используется конфигурация serilog через файлы.

2022-06-23 07:05 UTC, VVolchenkov commented on src/Web/Controllers/DevicesController.cs
> +        if (Devices.TryGetValue(device.Id, out _))
Изначально делал один метод, но т.к. точно не написано как хотят видеть API клиент, делал как владелец API максимально рестово

2022-06-23 07:10 UTC, VVolchenkov commented on src/Web/Program.cs
> +builder.Host.UseSerilog((_, lc) =>
понял

2022-06-23 07:11 UTC, VVolchenkov commented on src/Web/Controllers/DevicesController.cs
> +        if (Devices.TryGetValue(device.Id, out _))
Переделал

2022-06-23 07:11 UTC, VVolchenkov commented on src/Web/Controllers/DevicesController.cs
> +        if (Devices.Count <= 0)
Исправил

2022-06-23 10:01 UTC, merged