version-3 added db support
VVolchenkov/mobile-monitoring pull request #3
Opened 2022-06-23 14:54 UTC by VVolchenkov

2022-06-23 20:28 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/IRepository.cs
> +    Task<ICollection<T>> GetAll();
Btw: Если не секрет, то почему ICollection, а не IEnumerable?

2022-06-23 20:28 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +        var query = "SELECT * FROM devices WHERE id=2";
Хардкод остался

2022-06-24 06:13 UTC, SergerGood requested changes

2022-06-24 06:13 UTC, SergerGood commented on src/Infrastructure/Infrastructure/IRepository.cs
> +public interface IRepository<T>
Если появляется дженерик Repository + BaseEntity, то грех не сделать ограничение на тип T

2022-06-24 06:13 UTC, SergerGood commented on src/Web/Properties/launchSettings.json
> +        "ConnectionStrings:PostgreSql": "Server=127.0.0.1;Database=postgres;Uid=postgres;Pwd=superuser;"
Давай попробуем так. В environmentVariables будет для production конфигурации. И еще создадим appsettings.json для development, где тоже будет ConnectionString

2022-06-24 06:13 UTC, SergerGood commented on src/Web/Program.cs
> +builder.Services.AddInfrastructure(builder.Configuration.GetConnectionString("PostgreSql"));
Тут вроде можно сразу работать с configuration, она уже сбилжена если не ошибаюсь.
И еще. Может в метод передадим сам configuration и в методе уже будем получать значение строки подключения. Получается мы создали метод AddInfrastructure, который явно принимает строку подключения. Судя по его названию он более универсальный. В этом нет ничего плохого, но тогда лучше сразу передать конфигурацию в него.

2022-06-24 07:10 UTC, VVolchenkov commented on src/Web/Program.cs
> +builder.Services.AddInfrastructure(builder.Configuration.GetConnectionString("PostgreSql"));
Переделал сразу на использование Configuration.
Как только появится еще один connectionString или нужно будет что-то из Configuration, тогда можно и расширить передаваемое значение, а так смысла нагружать метод и читателя кода я не вижу

2022-06-24 07:20 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/IRepository.cs
> +public interface IRepository<T>
Ага, пропустил это

2022-06-24 07:34 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +        var query = "SELECT * FROM devices WHERE id=2";
Убрал

2022-06-24 07:37 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/IRepository.cs
> +    Task<ICollection<T>> GetAll();
Вообще на автомате пишу, но
ICollection даёт методы add, edit, remove, чаще всего в таких методах использовал IReadOnlyCollection, а если коллекцию предполагается редактировать то ICollection, IEnumerable только на вход, как по Рихтеру, на вход широкий диапозон, на выходе уже

2022-06-24 07:38 UTC, VVolchenkov commented on src/Web/Properties/launchSettings.json
> +        "ConnectionStrings:PostgreSql": "Server=127.0.0.1;Database=postgres;Uid=postgres;Pwd=superuser;"
Написал разные варианты, посмотри)

2022-06-24 07:44 UTC, SergerGood commented on src/Infrastructure/Infrastructure/IRepository.cs
> +public interface IRepository<T>
Видимо не в этом коммите)

2022-06-24 07:45 UTC, SergerGood approved these changes

2022-06-24 07:52 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/IRepository.cs
> +    Task<ICollection<T>> GetAll();
Меня больше наличие в ICollection методов для редактирования смутило. Ок, спасибо.

2022-06-24 07:53 UTC, pavelpykhtin approved these changes

2022-06-24 07:54 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/IRepository.cs
> +public interface IRepository<T>
По пути потерялось :)

2022-06-24 10:07 UTC, merged