version-5
VVolchenkov/mobile-monitoring pull request #5
Opened 2022-06-29 14:18 UTC by VVolchenkov

2022-06-29 14:42 UTC, pavelpykhtin requested changes

2022-06-29 14:42 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +    private readonly IUnitOfWork unitOfWork;
Может тогда сделать его protected в базовом классе?

2022-06-29 14:42 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/UnitOfWork.cs
> +public class UnitOfWork : IUnitOfWork, IDisposable
Добавь еще Rollback. Например, если не удалось файл на диск сохранить придется откатывать все сделанные изменения. Ошибка при этом за пределами UnitOfWork возникает и нужна ручка, за которую можно откатить транзакцию.

2022-06-30 07:46 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/UnitOfWork.cs
> +public class UnitOfWork : IUnitOfWork, IDisposable
Добавил

2022-06-30 07:50 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +    private readonly IUnitOfWork unitOfWork;
Точно protected, может internal? Protected UnitOfWork сделать не получится

2022-06-30 14:04 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +    private readonly IUnitOfWork unitOfWork;
Я про видимость поля, не самого класса.
Все отнаследованные классы будут использовать это поле, тогда зачем дублировать?

2022-06-30 14:19 UTC, pavelpykhtin commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +    private readonly IUnitOfWork unitOfWork;
Ладно, это не критично

2022-06-30 14:26 UTC, pavelpykhtin approved these changes

2022-07-01 07:36 UTC, VVolchenkov commented on src/Infrastructure/Infrastructure/Repositories/DeviceRepository.cs
> +    private readonly IUnitOfWork unitOfWork;
Всё, я понял, переделал

2022-07-01 11:59 UTC, merged